
default: vim tmux screen htop

vim:
	echo "app-editors/vim bash-completion vim-pager python ruby" > /etc/portage/package.use/vim
	emerge -uN vim{,-core}

tmux:
	emerge -uN tmux

screen:
	emerge -uN screen

htop:
	emerge -uN htop


