#!/bin/bash
set -x
pip install -q -I ~/.virtualenvs/external/ipython
pip install -q -I ~/.virtualenvs/external/pytest
pip install -q -I ~/.virtualenvs/external/nose
pip install -q -I --no-deps ~/.virtualenvs/external/ipdb
pip install -q -I ~/.virtualenvs/external/line_profiler
hash -r
set +x
