#!/bin/bash

if command -v brew &> /dev/null; then
    # -- coreutils
    #export PATH="$(brew --prefix coreutils)/libexec/gnubin":${PATH}
    export PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}
    # -- python
    #export PATH="$(brew --prefix python)/bin":/usr/local/share/python:${PATH}
    export PATH=/usr/local/opt/python/libexec/bin:${PATH}
    # -- ruby
    #export PATH="$(brew --prefix ruby)/bin":${PATH}
    export PATH=/usr/local/opt/ruby/bin:${PATH}
fi
